### PR TITLE
fix(shiki): enable WASM on CF deployment

### PR DESCRIPTION
**Pull request by farnabaz**

### CODE REVIEW

**Comment by adamdehaven** [comment]
🎉  @farnabaz - when this is released I can pull it in and verify in our app; thanks for the update!

**Comment by farnabaz** [comment]
You can check this using edge version. Add `"@nuxtjs/mdc": "npm:@nuxtjs/mdc-edge@latest"` to your `package.json`

**Comment by adamdehaven** [comment]
@farnabaz I think there's still a missing internal configuration and/or missing piece of documentation. When deploying to Cloudflare Pages, I still need to define `shiki/onig.wasm` to my externals in my `nuxt.config`:

```typescript
vite: {
  build: {
    rollupOptions: {
      external: [
        'shiki/onig.wasm',
      ],
    },
  },
}
```

If I exclude this from my build settings, I still get an error in the `build` step:
could not load wasm error

Could the `addWasmSupport` util you added also push the `shiki/onig.wasm` entry to the `vite.build.rollupOptions.external` array if it doesn't exist? Otherwise, I think this needs to be added to the docs.

**Comment by adamdehaven** [comment]
@farnabaz any chance a new release could be published on the `@latest` channel with these changes?

**Pull request merged**
