### PR TITLE
chore: bump `@nuxt/module-builder`

### PR DESCRIPTION
**Pull request by danielroe**
resolves https://github.com/nuxt-modules/mdc/issues/218

### CODE REVIEW

**Comment by adamdehaven** [comment]
Yes 🎉  thanks Daniel!

**Review by farnabaz — APPROVED** [review]

**Comment by adamdehaven** [comment]
@danielroe @farnabaz when I run the build that includes this dependency update, I'm still seeing the exported `ModuleOptions` in the `/dist/types.d.ts` file, meaning when I pull into my Nuxt project, I the `nuxt.config.ts` type errors from #218 still persist.

**Comment by danielroe** [comment]
There should still be an exported ModuleOptions. But it should not be within the Nuxt/schema augmentation.

**Comment by adamdehaven** [comment]
I installed `@nuxtjs/mdc-edge@0.8.1-28636409.6425fec`

You're correct, the config options are no longer leaking out (I must not have restarted TS); however, there's a new issue whereby the `highlight` option's exported interface is now only `boolean` rather than [the full interface](https://github.com/nuxt-modules/mdc/blob/6425fec567de9f102f3dbdc5d1fbcc56c9f194b7/src/types.ts#L19-L65).
image

```md
Type '{ highlighter: string; themes: string[]; theme: string; langs: string[]; }' is not assignable to type 'boolean | undefined'.
```

**Comment by danielroe** [comment]
Ah, that might happen if this module doesn’t export ModuleOptions.

**Pull request merged**
