### PR TITLE
fix: add line break to end of each code block line

### PR DESCRIPTION
**Pull request by nobkd**
Similar to nuxt/content#2008 to fix nuxt/content#1883

Current solution not working.

Not even sure, why this shouldn't work. If you have any idea, please let me know!

---

Do I have to add it as text node of real element? 🤔

Would have to traverse hast to find the last text node in line and add `\n` to its value.
For empty lines, will probably have to add new span?

(Maybe applying `\200b` to non-empty lines because of adding `\n` to empty ones?)

### CODE REVIEW

**Comment by farnabaz** [comment]
Hey @nobkd 
It is strange because for it seems fine in Firefox. Just checked https://content.nuxt.com/get-started/installation#add-to-a-project

**Comment by nobkd** [comment]
I've checked again, and the `hast` really still contains the `\n`s at the end of each line of a code block.
I'll check the code again, because it still not works in FF for me, even after purging cache or switching devices...

**Comment by nobkd** [comment]
The version I just pushed, only works for lines that contain code / text.
Currently, empty lines will be dropped when copying by hand in Firefox.

**Comment by nobkd** [comment]
@farnabaz do you have thoughts about how to properly solve this?

**Comment by nobkd** [comment]
I don't think, that newlines should be [added to inline `code`s](https://github.com/nuxt-modules/mdc/pull/62/files#diff-4afbbe8e3436a3a78c87cb7cf7daefeecd7c52923a1f27fa344c08f695a4e858)

The code where the [`newline` is added to a *text node*](https://github.com/nuxt-modules/mdc/pull/62/files#diff-4909653ea47f6095fb4863dc00735c82495a6dad29ed6e05bdfab1763498751eR85-R91) seems to need a check, if the code is a `code` block or an inline `code`.

(Also not sure, if an *empty line placeholder* gets added to empty inline `code`s.)

**Pull request merged**
