### PR TITLE
feat(parser): new `createProcessor` util

### PR DESCRIPTION
**Pull request by sandros94**
### 🔗 Linked issue

Discussed in #285

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR introduces a new `createProcessor` util without breaking changes.

It returns an object containing both the parser (the original implementation for `createMarkdownParser`) as well as the `processor` itself, allowing for further customization and reuse or the processor for future implementations.

#### Author's note

I'm not a super fan of this approach, but unfortunately because of this very [`options.toc`](https://github.com/nuxt-modules/mdc/blob/5250e660f8544138c6475725ad19d8ee01ac2110/src/runtime/parser/index.ts#L115) it is the only way to add this functionality without introducing a breaking change. But considering that many other modules (for example Nuxt's Content) are being refactored to new majors we could take this into consideration.

### CODE REVIEW

**Comment by farnabaz** [comment]
Thanks for PR,
I didn't get your point about `options.toc`.

**Comment by sandros94** [comment]
> Thanks for PR, I didn't get your point about `options.toc`.

Scratch that 😜
I just realized that I was mixing up local and global variables and I might have a nicer solution

**Comment by sandros94** [comment]
@farnabaz sorry if I made a bit of confusion about `options.toc`, I didn't notice that there is no `toc` inside `moduleOptions`.

In [f88d594](https://github.com/nuxt-modules/mdc/pull/289/commits/f88d594f27c0d696ca077b36e920d2b115f3b591) I managed simplify even further the `createProcessor` and `createMarkdownParser` without any breaking change.

Now if we only need the processor we simply do:
```ts
const processor = await createProcessor(inlineOptions)
```

**Review by farnabaz — APPROVED** [review]
Thanks 👍

**Pull request merged**
